package com.outlook.hxsw.settlements.entities.folk;

import net.minecraft.world.entity.ai.goal.Goal;

import javax.annotation.Nullable;

class FolkActionGoal extends Goal {
    /**
     * 执行 {@link FolkEntity#getCurrentAction()} 的桥接 Goal。
     * <p>
     * 关键语义：当 {@link FolkEntity#setAction(FolkAction, java.util.function.Consumer, Runnable, java.util.function.Consumer)}
     * 用一个新动作覆盖旧动作后，下一次 AI tick 中 {@link #canContinueToUse()} 会因为引用不相等而返回 false。
     * Vanilla 的 GoalSelector 会随即调用 {@link #stop()}，从而对旧动作调用 {@link FolkAction#interrupt()}。
     * <p>
     * 注意：这里的 "interrupt" 表示动作被更高优先级/新动作打断，并不等同于 cancel；此处不会自动回环到逻辑线程。
     */ // -- generated by GPT-5.2
    private final FolkEntity folk;
    private @Nullable FolkAction<?> activeAction;

    FolkActionGoal(FolkEntity folk) {
        this.folk = folk;
    }

    @Override
    public boolean canUse() {
        var action = this.folk.getCurrentAction();
        this.activeAction = action;
        return action != null;
    }

    @Override
    public boolean canContinueToUse() {
        return this.activeAction != null && this.activeAction == this.folk.getCurrentAction();
    }

    @Override
    public void start() {
        if (this.activeAction != null) {
            this.activeAction.start();
        }
    }

    @Override
    public void tick() {
        if (this.activeAction != null) {
            this.activeAction.tick();
        }
    }

    @Override
    public void stop() {
        if (this.activeAction != null) {
            this.activeAction.interrupt();
            this.activeAction = null;
        }
    }
}
